services:
  - type: web
    name: durian-map-backend
    env: bun
    rootDir: backend
    buildCommand: bun install
    startCommand: bun run src/index.ts
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
